### ISSUE TITLE
See current mappings/change mappings

### ISSUE THREAD

**Issue by gatoWololo** [amibiz/ergo-keys#2]
Hello! Thank you for the great plugin.

Coming from emacs I was excited to see someone had implemented modal key bindings.

I can't seem to find the list of keybindings? And is it possible to change what command the keys bind to?

**Comment by amibiz** [comment]
Thanks @gatoWololo 

The list of key bindings are not documented. From the source code https://github.com/amibiz/ergo-keys/blob/7ccbacc96dd907feb6ae403321a76d9c2ceb73d3/src/main/java/com/github/amibiz/ergokeys/ErgoKeysPlugin.java#L38-L132
The first key code is for QWERTY and the second for Dvorak. Also note the _leader_ key bindings for an extra layer of commands. Currently, the leader key is mapped to the _space_ key. For example, `SPACE + J` and `SPACE + L` will navigate the editor back and forward respectively.

Regarding changes to the key bindings, it is hard coded.

I have opened two issues to address the above:

- #3 Document all supported key bindings
- #4 Support custom key bindings

**Comment by amibiz** [comment]
@gatoWololo FYI, all supported key bindings are now documented in the README (ref #5)

**Comment by gatoWololo** [comment]
This is great. Thank you!

**Comment by amibiz** [comment]
@gatoWololo @amynbe 

PR #16 introduces support for custom CMD mode key bindings. You can now select the CMD mode keymap using the settings dialog `File -> Settings -> Keymap` and modify shortcuts. Also, default shortcuts are merged into CMD mode keymap (e.g. `Ctrl + B` and `Ctrl + Button1 Click` for _GotoDeclaration_).

**Comment by amibiz** [comment]
Support for custom key binding is now available in latest update (v1.9).
Closing issue.
