### ISSUE TITLE
Custom Keybindings And Switching to Insert Mode

### ISSUE THREAD

**Issue by gatoWololo** [amibiz/ergo-keys#29]
There is a problem with command-mode custom keybindings that open pop-up windows or menus. The menu or window will open but I will be stuck on command-mode with the key to switch to insert-mode not working. Basically, we need to switch to insert-mode before performing the action. I think you have also ran into this problem and that's why this piece of code exists:
```java

                if (action.getClass().equals(SearchEverywhereAction.class) ||
                        action.getClass().equals(RunAnythingAction.class) ||
                        action.getClass().equals(IncrementalFindAction.class) ||
                        action.getClass().equals(FindInPathAction.class) ||
                        action.getClass().equals(ViewStructureAction.class)) {
                    final Editor editor = dataContext.getData(CommonDataKeys.EDITOR);
                    activateInsertMode(editor);
                }
```
This fixes the issues for these specific actions, but obviously can never cover all the different actions I want to bind to keys.

This is my current minimal solution:
1) Whenever the focus is lost, I activate insert mode (We lose focus for actions that create a pop-up window). The idea being that we only want to be in command-mode in the "main" editor where we actually edit code, so whenever whenever focus is lost on this editor we probably want to be in insert mode.
2) When we gain focus we check if the editor is editing a named file. (Editor seems to be a generic named used for many things we can type into, including pop-up windows, etc). But only the "main" editor has named files we are modifying. So when we gain focus on the main editor we switch back to command mode. This is pretty much the entire change:
```diff
         EditorFactory.getInstance().addEditorFactoryListener(
                 new EditorFactoryListener() {
                     @Override
                     public void editorCreated(@NotNull EditorFactoryEvent event) {
                         Editor editor = event.getEditor();
+
                         editor.getContentComponent().addFocusListener(new FocusListener() {
                             @Override
                             public void focusGained(FocusEvent focusEvent) {
-                                LOG.debug("focusGained: focusEvent=", focusEvent);
-                                editor.getSettings().setBlockCursor(inCommandMode());
+                                LOG.debug("focusGained: focusEvent=", focusEvent.toString());
+
+                                EditorComponentImpl e = (EditorComponentImpl)(focusEvent.getSource());
+                                VirtualFile f = e.getEditor().getVirtualFile();
+                                // No file name. Assume it is not the "main" editor windows where user modifies code.
+                                if(f != null){
+                                    activateCommandMode(editor);
+                                }
                             }
 
                             @Override
                             public void focusLost(FocusEvent focusEvent) {
                                 LOG.debug("focusLost: focusEvent=", focusEvent);
-                                lastEditorUsed = editor;
+                                // Will we need this?
+//                                lastEditorUsed = editor;
+                                activateInsertMode(editor);
                             }
                         });
                     }
```
I have been using this for a while and seems to work well. Other approaches that I tried had corner cases I couldn't easily handle. I have a fork of this repo but it is cumbersome to maintain and merge new changes.

I'd be happy to make a PR with these changes if there is interest? Thanks

**Comment by amibiz** [comment]
Yes, a PR with a fix would be great :) as the current behavior of getting "stuck" in command mode breaks the flow.

some notes:

1. why not remove the `if` in https://github.com/amibiz/ergo-keys/blob/f6e16903086400a5e39a2c775762699314544de7/src/main/java/com/github/amibiz/ergokeys/ErgoKeysPlugin.java#L151-L158
   and always activate insert mode?
2. does the solution of checking for named files in `focusGained` also take into account scratch files?

**Comment by amibiz** [comment]
@vqns I think the terminal can be solved specifically. Can you please open an issue and I will take a look? Thanks!
