### ISSUE TITLE
Update to 2022.3.*

### ISSUE THREAD

**Issue by porcinity** [amibiz/ergo-keys#36]
This plugin isn't compatible with the latest IntelliJ and Rider versions (2022.3.*). Could you publish an update?

**Comment by amibiz** [comment]
Thanks @porcinity 

I have updated the plugin in JetBrains Marketplace and it should be available in a few days.

**Comment by porcinity** [comment]
Thanks so much for updating this wonderful plugin---I'm excited to use it! @amibiz

**Comment by amibiz** [comment]
Updated plugin for 2022.3 is available in marketplace, closing issue.
