### ISSUE TITLE
Binding Escape key to Command Mode has no effect

### ISSUE THREAD

**Issue by Tsilkow** [amibiz/ergo-keys#39]
I wanted to reproduce vim's exit from insert mode by pressing escape key, but I can't seem to do so.
I've added a custom binding for Command Mode to do that (I've had to do it directly in file), but Pressing escape does nothing. I've also removed all other mappings for escape key, but nothing changed.

Binding Insert Mode to Escape has some weird consequences too: insert mode is entered, but only after second press.

Can Escape a viable key for command mode/insert mode?

**Comment by Tsilkow** [comment]
I figured it out, I didn't realize that entering Command/Insert mode meant changing the keymap.
I'd love to see that better documented.

**Comment by amibiz** [comment]
Yes, unfortunately your correct and it is not documented anywhere.
I have added an issue to address it #40.

Can you add it to the README and submit a PR? that would be very helpful.
