### ISSUE TITLE
Mouse shortcuts don't work in command mode

### ISSUE THREAD

**Issue by amynbe** [amibiz/ergo-keys#6]
First of all thanks for writing this plugin.
I've started using it today and am liking it. I've also noticed the following problems:
- Middle click (or Ctrl+Click) on an identifier no longer goes to declaration/usages if you're in command mode.
- i j k l keys don't insert the corresponding char in "search everywhere"(shift-shift) and "run anything" (ctrl-ctrl)
- Non-Xah shortcuts don't work in command mode (e.g Ctrl+N for go to class)
- Alt-space doesn't work on my system (windows 10). It triggers the OS window menu (with Restore, Move, etc) and had to remap to Alt-F (which normally triggers the File menu but you can still do that with another hit of Alt-F)

I think we can live with most of these issues but the first one would definitely need to be fixed, if possible. As neither of mouse-based and keyboard-based input mode can ever totally replace one another, any software should provide optimal support for both.

Also, I created a visual layout of the plugin's Keymap on keyboard-layout-editor.com, as a way to help familiarise myself quickly with it: [ErgoKeysV0](http://www.keyboard-layout-editor.com/#/gists/a8580928ecd9d38a04dded8eb23be192). Might come in handy for other new users.

**Comment by amibiz** [comment]
Thanks @amynbe 

1. opened issue https://github.com/amibiz/ergo-keys/issues/7
2. does not reproduce locally for me, can you please provide the following: product/version, os, keyboard layout (you can use the copy icon in Help -> About)
3. opened issue https://github.com/amibiz/ergo-keys/issues/8
4. opened issue https://github.com/amibiz/ergo-keys/issues/9 (what do you think is an easy shortcut and not taken in windows 10 for command mode?)

The visual keyboard layout [ErgoKeysV0](http://www.keyboard-layout-editor.com/#/gists/a8580928ecd9d38a04dded8eb23be192) is a great idea, can you make another one for Dvorak and add it to the README?

**Comment by amynbe** [comment]
Thanks for that.

Here's my config:
Build #IU-201.7846.76
Windows 10 10.0
QWERTY US

Regarding an Alt-space replacement, I can think of Esc or Alt+F. Alternatively, a more complex to implement approach would be double press on a key that's unlikely to be double pressed, such as ',,' - as demonstrated here with jj: https://vim.fandom.com/wiki/Avoid_the_escape_key (this works in ideaVim). Actually there's also Alt-D that's a super easy shortcut not taken anywhere in Intellij. 

I'll do a Dvorak version of the visual layout when I get a minute this week(-end) and PR to the README.

**Comment by amibiz** [comment]
Fixed #7 #9

I added `Shift + Space` shortcut in addition to `Alt + Space`. Used it before and found it easy and it is not used by Windows OS according to https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts.

Also uploaded a new version of the plugin with the fixes (note that it takes  2 business days for JetBrains to approve the update).

Regarding the issue with _search everywhere_, how are you invoking it? `Shift + Shift` or `<CMD Mode> + A`?

**Comment by amynbe** [comment]
Hi,
it's `Shift + Shift` from command mode. It doesn't happen when triggered from editing mode.

Regarding `Shift + Space` it sounds good except if someone is typing space-separated upper case words. I don't recall myself doing that often at all, and it can be worked around by being careful when typing, so I don't know whether it's worth considering.

**Comment by amibiz** [comment]
Reproduced and opened issue https://github.com/amibiz/ergo-keys/issues/13

**Comment by amibiz** [comment]
Fixes for all issues above are available in latest update (v1.9).
Closing issue.
